### ISSUE TITLE
Client-side javascript not working in Meteor v1.3 Beta

### ISSUE THREAD

**Issue by huttonr** [huttonr/bootstrap3#6]
Using `Meteor v1.3-modules-beta.4` there is an browser console warning displayed: _Bootstrap disabled. Create a file named 'bootstrap-settings.json' to enable._

**Essentially, the client-side Bootstrap javascript appears to not be loading in Meteor v1.3.**

**Comment by emgee3** [comment]
@huttonr, I spent a little time looking into this. Part of the problem seems to be that the `ecmascript` package dependency is fixed to a specific version, which is quite a bit older than the one used in Meteor 1.3-beta.4 — you're using 0.1.6 vs 0.3.1-modules.4.

I then attempted to check the same issue with the -assets package, but the build step ran out of control and I actually had to reboot my computer to get it to stop.

I suggest trying to remove the hard-coded 0.1.6 version, _but build the packages using Meteor 1.2.1, not the beta_.

**Comment by huttonr** [comment]
@emgee3 
Unfortunately the version constraint is required for `meteor publish`.

I've dug into this a bit more and the problem seems to lie in the [.addJavaScript line](https://github.com/huttonr/bootstrap3/blob/master/plugin/bootstrap3.js#L84).

For some reason that function is straight-up not working and I'm not sure if it's a Meteor issue such as a version conflict with where exactly javascript files are stored, but currently nothing added with .addJavascript is running on the client or server.  Possibly with the webpack ==> browserify change.  

Haven't got my finger on it yet.

**Comment by huttonr** [comment]
After a lot of further testing this is definitely a bug and appears to be unrelated to the `ecmascript` package.

https://github.com/meteor/meteor/issues/6014

**Comment by emgee3** [comment]
Spent a bit more time on this and you're right. It affects JSON sources but not arbitrary extensions. I've created an issue https://github.com/meteor/meteor/issues/6017. Though a workaround would be rename the .json extension to .bootstrap, though as this would be breaking, it would be preferable to get it fixed in Meteor.

**Comment by emgee3** [comment]
Any my notifications are wonky, because now I see that you already reported...

**Comment by huttonr** [comment]
Weird, I haven't gotten a response in changing the file extension.

**Comment by huttonr** [comment]
This was now fixed in Meteor `1.3-beta.11`.
